apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-frontend
  template:
    metadata:
      labels:
        app: fabric-frontend
    spec:
      containers:
      - name: frontend
        image: katsdros/fabric-frontend:v1  # my registry docker
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fabric-frontend-service
spec:
  selector:
    app: fabric-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002  # access from http://localhost:30002
  type: NodePort