apiVersion: apps/v1
kind: Deployment
metadata:
  name: thingsboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thingsboard
  template:
    metadata:
      labels:
        app: thingsboard
    spec:
      containers:
      - name: thingsboard
        image: thingsboard/tb-postgres
        ports:
        - containerPort: 9090
          name: web
        - containerPort: 1883
          name: mqtt
        env:
        # setting for quick start
        - name: TB_QUEUE_TYPE
          value: "in-memory"
---
apiVersion: v1
kind: Service
metadata:
  name: thingsboard-service
spec:
  type: NodePort
  selector:
    app: thingsboard
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30003  # list to port:30003
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883 # internal port for Node-RED